# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/site_ruby/all/site_ruby.rbi
#
# site_ruby-3.2.0

module Gem
end
class Gem::Security::Policy
  include Gem::UserInteraction
end
module Gem::Security
end
class Gem::Security::TrustDir
end
class Gem::Security::Signer
  include Gem::UserInteraction
end
class Gem::Security::Exception < Gem::Exception
end
class Gem::Package::DigestIO
end
class Gem::Package::Source
end
class Gem::Package::FileSource < Gem::Package::Source
end
class Gem::Package::IOSource < Gem::Package::Source
end
class Gem::Package::Old < Gem::Package
end
class Gem::Package::TarHeader
end
class Gem::Package::TarReader::Entry
end
class Gem::Package::TarReader
  include Enumerable
end
class Gem::Package::TarReader::UnexpectedEOF < StandardError
end
class Gem::Package::TarWriter
end
class Gem::Package::TarWriter::FileOverflow < StandardError
end
class Gem::Package::TarWriter::BoundedStream
end
class Gem::Package::TarWriter::RestrictedStream
end
class Gem::Package
  include Gem::UserInteraction
end
class Gem::Package::Error < Gem::Exception
end
class Gem::Package::FormatError < Gem::Package::Error
end
class Gem::Package::PathError < Gem::Package::Error
end
class Gem::Package::SymlinkError < Gem::Package::Error
end
class Gem::Package::NonSeekableIO < Gem::Package::Error
end
class Gem::Package::TooLongFileName < Gem::Package::Error
end
class Gem::Package::TarInvalidError < Gem::Package::Error
end
